# -*- coding: utf-8 -*-
"""Copy of sba2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KOMJFFi4KyOgSSmeIrF6cx726S3LoHM

## Cara simpan: klik `file` -> `Download .py`. kemudian upload ke netacad di soal anda. 
**NOTE: SEBELUM ANDA SUBMIT SILAKAN DIJALANKAN TERLEBIH DAHULU APAKAH SCRIPT/KODE ANDA BEBAS DARI ERROR ATAU TIDAK**.
"""

'''
namafile: sba.py
Lembar kerja/script Latihan SBA
'''
# >>>>>>LEMBAR KERJA>>>>>>>>>
# lembar ini hanya berisi pendefinisian fungsi dan class saja
 
#email netacad
email = 'oeiairy.utomo@gmail.com'
 
# >>>>>>Soal 1
def fungsiIO():
  input_angka = (input('Masukan angka = '))
  print(input_angka)
  input_angka = sorted(list(map(int,input_angka.split())))
  
  for i in input_angka:
      print('*'*i)

  
 
# >>>>>>Akhir Soal 1 
 
# >>>>>>Soal 2
def caseShopia(txt):
  txt_baru=''
  for ch in txt :
    if ch.isalpha() and ch.islower():
      txt_baru+=ch.upper()

    elif ch.isalpha() and ch.isupper():
      txt_baru+=ch.lower()

    else :
      continue

  return txt_baru
  
  
# >>>>>>Akhir Soal 2 
 
# Jangan diubah biarkan seperti ini
dcur2idr = {'USD': 14425, 'EUR': 16225, 'AUD': 9925, 'CAD': 10500, 
             'GBP': 17800, 'CHF': 15200, 'SGD': 10375, 'HKD': 1775, 
             'JPY': 132500, 'MYR': 3250, 'SAR': 3500, 'WON': 10750, 
             'IDR': 1}
 
# >>>>>> Soal 3 
def usd2eur(usd):
  usd_2euro = usd*dcur2idr['USD']/dcur2idr['EUR']
  return float(usd_2euro)
  
 
 
# >>>>>>Akhir Soal 3 
 
 
# >>>>>>Soal 4 
class MoneyChanger:
  def __init__(self,dcurrency,base='IDR',percent=2):
    self.dcurrency = dcurrency
    self.base = base
    self.percent = percent
    
 
  def selling_price(self,nominal,curr):
    sell_price= (nominal*self.dcurrency[curr]/self.dcurrency[self.base])*(1+(self.percent/100))
    return sell_price
    # Mulai kode anda dari sini
 
  def buying_price(self,nominal,curr):
    buy_price= (nominal*self.dcurrency[curr]/self.dcurrency[self.base])*(1-(self.percent/100))
    return buy_price
    # Mulai kode anda dari sini
 
  def change_base(self,new_base):
    self.base = new_base
    
 
fungsiIO()
# >>>>>>Akhir Soal 4 
 
# >>>>>>AKHIR LEMBAR KERJA>>>>>>>>>
 
